extern char pause();
extern void video_set_cursor(int x, int y); 
extern void tohex(long int number, char capitalized);
extern int query_drive_inserted(char drive);
extern void reboot();
extern void load_sector(char drive, long int dest_sector, long int real_sector);
extern void load_executable();
extern char* get_word(char* string, int pos);
extern char* atoi(long int n);
extern void toint(long int n);
extern void video_save_cursor();
extern void video_load_cursor();
extern void printf(char* str);
